In [ ]:
import torch

In [ ]:
def activation(x):

  """ Sigmoid activation funtion
      Arguments
      ----------------
      x: torch.Tensor

  """
  return 1/(1+torch.exp(-x))

In [ ]:
#generate dummy data

torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [ ]:
y=activation(torch.sum(features*weights) + bias)
#y=activation((features*weights).sum() + bias)

In [ ]:
y

tensor([[0.1595]])

In [7]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [8]:
y

tensor([[0.1595]])

In [9]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [10]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [11]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.04634636, 0.6347036 , 0.72047288],
       [0.27436252, 0.33376497, 0.61780718],
       [0.95626835, 0.79652261, 0.26306387],
       [0.93309265, 0.10460485, 0.24979071]])

In [12]:
b = torch.from_numpy(a)
b

tensor([[0.0463, 0.6347, 0.7205],
        [0.2744, 0.3338, 0.6178],
        [0.9563, 0.7965, 0.2631],
        [0.9331, 0.1046, 0.2498]], dtype=torch.float64)

In [13]:
b.numpy()

array([[0.04634636, 0.6347036 , 0.72047288],
       [0.27436252, 0.33376497, 0.61780718],
       [0.95626835, 0.79652261, 0.26306387],
       [0.93309265, 0.10460485, 0.24979071]])

In [14]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.0927, 1.2694, 1.4409],
        [0.5487, 0.6675, 1.2356],
        [1.9125, 1.5930, 0.5261],
        [1.8662, 0.2092, 0.4996]], dtype=torch.float64)

In [15]:
a

array([[0.09269272, 1.26940721, 1.44094576],
       [0.54872504, 0.66752993, 1.23561435],
       [1.9125367 , 1.59304521, 0.52612775],
       [1.86618529, 0.2092097 , 0.49958142]])